### ISSUE TITLE
Link to "release" resulting in 404...

### ISSUE THREAD

**Issue by mcterrySep** [ridiculousness/cookbook.gitextensions#1]
Hello - it appears that the release this tool is pointing to is version 2.48 and so I'm getting a 404 when trying to include this recipe.

>         [2017-02-28T17:06:05-05:00] ERROR: Error connecting to https://github.com/gitextensions/gitextensions/releases/download/v2.48.05/GitExtensions-2.48.05-SetupComplete.msi, retry 1/5
>        [2017-02-28T17:06:12-05:00] ERROR: Error connecting to https://github.com/gitextensions/gitextensions/releases/download/v2.48.05/GitExtensions-2.48.05-SetupComplete.msi, retry 2/5
>        [2017-02-28T17:06:18-05:00] ERROR: Error connecting to https://github.com/gitextensions/gitextensions/releases/download/v2.48.05/GitExtensions-2.48.05-SetupComplete.msi, retry 3/5
>        [2017-02-28T17:06:25-05:00] ERROR: Error connecting to https://github.com/gitextensions/gitextensions/releases/download/v2.48.05/GitExtensions-2.48.05-SetupComplete.msi, retry 4/5
>        [2017-02-28T17:06:31-05:00] ERROR: Error connecting to https://github.com/gitextensions/gitextensions/releases/download/v2.48.05/GitExtensions-2.48.05-SetupComplete.msi, retry 5/5
>        
>              
>              ================================================================================
>              Error executing action `create` on resource 'remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\GitExtensions-2.48.05-SetupComplete.msi]'

What are your thoughts on pointing to the "latest" release via this URL...

> https://github.com/gitextensions/gitextensions/releases/latest

**Comment by evandervecht** [comment]
The cookbook has been created in a way that you can override the default['git-extensions']['version'] = '2.48.05' attribute either from a Chef Environment/Role or Node attribute.

Another way is to update this cookbook per version but that would mean that I need to check every once in a while if a new version has been created. 

This is the latest download string:
https://github.com/gitextensions/gitextensions/releases/download/v2.49/GitExtensions-2.49-SetupComplete.msi

Meaning if you override the default['git-extensions']['version'] = '2.48.05' to default['git-extensions']['version'] = '2.49' it should download the latest version.

As this repo has not been updated for quitte a while I will make a newer release with the 2.49 release.

**Comment by evandervecht** [comment]
@mcterrySep; I uploaded a new version of the cookbook (v.0.1.1) to the Chef supermarket. This one supports v2.49 of Git Extensions. Please test and let me know if this resolved it.

**Comment by mcterrySep** [comment]
Thank you @ridiculousness -- my issues are resolved! Thank you for showing me how to configure the version as well...greatly appreciated.
